#!/usr/bin/env python3
"""
Measure the correction engine: CER/WER before vs after, and fixed/broke counts.

This is the gate every change to pipeline/correction/ has to clear. CER alone
is not enough for this project. The corpus goal cares more about precision than
coverage -- a confidently wrong "fix" silently corrupts training data in a way
that is much harder to catch downstream than an untouched OCR error. So the
report separates:

    fixed  the engine changed a word and the reference agrees with the new word
    broke  the engine changed a word the reference already agreed with
    other  the word was wrong before and is still not right -- noise moved around

An engine that lowers CER while raising `broke` is not an improvement here.

Three input modes:

    --pages 'tests/fixtures/eval/*.png'   OCR real page images; ground truth is
                                          the same-basename .txt (build a set
                                          with tools/build_eval_set.py)
    --text-pair noisy.txt clean.txt       an already-OCR'd file and its reference
    --synthetic 200                       corrupt N clean corpus lines and
                                          measure recovery -- no ground truth
                                          needed

CAVEAT ON --synthetic: the noise is generated by inverting the corrector's own
GLYPH_CONFUSIONS table, so it tests the engine against exactly the error model
it was built around. That structurally flatters the result. It is a smoke test.
Real pages (--pages) are the gate.
"""

import argparse
import difflib
import glob
import json
import os
import random
import re
import sys
import time
from typing import Any, Dict, List, Optional, Tuple

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pipeline import init_pipeline
from pipeline.correction import correct_layout_lines
from pipeline.correction.edit_distance import GLYPH_CONFUSIONS
from tools.ocr_bench import char_error_rate, word_error_rate

KANNADA_RE = re.compile(r'[ಀ-೥]')
MATRAS = 'ಾಿೀುೂೃೆೇೈೊೋೌಂ್'


class Doc:
    """One benchmark unit: OCR/noisy lines plus the reference text for them."""

    def __init__(self, name: str, lines: List[Dict[str, Any]], reference: str):
        self.name = name
        self.lines = lines
        self.reference = reference

    @property
    def raw_text(self) -> str:
        return '\n'.join(l['text'] for l in self.lines)


# ─────────────────────────────────────────────────────────────
# Input loaders
# ─────────────────────────────────────────────────────────────

def load_page_docs(paths: List[str], lang: str, psm: int, oem: int) -> List[Doc]:
    """OCR each image once; ground truth is the same-basename .txt file."""
    from pipeline.ingestion import load_and_preprocess_image, normalize_resolution, preprocess_for_ocr
    from pipeline.ocr import ocr_image_with_layout

    docs = []
    for path in paths:
        gt_path = os.path.splitext(path)[0] + '.txt'
        if not os.path.exists(gt_path):
            print(f"  skipping {os.path.basename(path)}: no {os.path.basename(gt_path)} alongside it")
            continue

        img = load_and_preprocess_image(path, enhance_contrast=False)
        img = preprocess_for_ocr(normalize_resolution(img))
        lines = ocr_image_with_layout(img, lang=lang, psm=psm, oem=oem)
        reference = open(gt_path, encoding='utf-8').read()
        docs.append(Doc(os.path.basename(path), lines, reference))
    return docs


def load_text_pair(noisy_path: str, clean_path: str) -> List[Doc]:
    noisy = open(noisy_path, encoding='utf-8').read()
    clean = open(clean_path, encoding='utf-8').read()
    lines = [{'text': l} for l in noisy.split('\n')]
    return [Doc(os.path.basename(noisy_path), lines, clean)]


# Reverse of the optical confusion matrix: for each character the corrector
# knows can be *misread as* something else, the things it gets misread as. Used
# only to manufacture test noise -- the corrector never sees this table.
def _confusion_sources() -> Dict[str, List[str]]:
    sources: Dict[str, List[str]] = {}
    for wrong, options in GLYPH_CONFUSIONS.items():
        if len(wrong) != 1:
            continue
        for right, _cost in options:
            if len(right) == 1:
                sources.setdefault(right, []).append(wrong)
    return sources


def corrupt_line(line: str, rate: float, rng: random.Random, sources: Dict[str, List[str]]) -> str:
    """
    Inject OCR-shaped damage: optically confusable glyph swaps, dropped matras,
    and spurious intra-word spaces -- the three failure modes the correction
    engine is built around.
    """
    chars = list(line)
    n_edits = max(1, int(len(chars) * rate))
    for _ in range(n_edits):
        if not chars:
            break
        i = rng.randrange(len(chars))
        ch = chars[i]
        roll = rng.random()
        if roll < 0.5 and ch in sources:
            chars[i] = rng.choice(sources[ch])
        elif roll < 0.8 and ch in MATRAS:
            chars[i] = ''
        elif KANNADA_RE.match(ch) and 0 < i < len(chars) - 1:
            chars[i] = ch + ' '
    return ''.join(chars)


def load_synthetic_docs(
    count: int,
    corpus_dir: str,
    rate: float,
    seed: int,
    min_words: int = 6
) -> List[Doc]:
    rng = random.Random(seed)
    files = sorted(glob.glob(os.path.join(corpus_dir, '*.txt')))
    if not files:
        raise SystemExit(f"No .txt corpus files under {corpus_dir}")

    pool: List[str] = []
    rng.shuffle(files)
    for path in files:
        with open(path, encoding='utf-8', errors='ignore') as fh:
            for raw in fh:
                line = ' '.join(raw.split())
                if len(line.split()) >= min_words and KANNADA_RE.search(line):
                    pool.append(line)
        if len(pool) >= count * 20:
            break

    if not pool:
        raise SystemExit(f"No usable Kannada lines found under {corpus_dir}")

    sources = _confusion_sources()
    picked = rng.sample(pool, min(count, len(pool)))
    return [
        Doc(f"syn{i:04d}", [{'text': corrupt_line(clean, rate, rng, sources)}], clean)
        for i, clean in enumerate(picked)
    ]


# ─────────────────────────────────────────────────────────────
# Change classification
# ─────────────────────────────────────────────────────────────

def _word_spans(text: str) -> List[Tuple[int, int, str]]:
    return [(m.start(), m.end(), m.group()) for m in re.finditer(r'\S+', text)]


def _locate(
    correction: Dict[str, Any],
    raw_spans: List[Tuple[int, int, str]],
    used: set
) -> Optional[int]:
    """
    Word index in the raw text that a correction refers to.

    Offset first, then a string fallback, because the two are not always in the
    same coordinate space: when heal_split_tokens merges a space-split word the
    corrector reports offsets into the pre-heal text, while later corrections
    on the same line are measured against the post-heal text. The fallback
    takes the first occurrence of the original word not already claimed by an
    earlier correction.
    """
    start = correction.get('start')
    if start is not None:
        idx = next((n for n, (s, e, _) in enumerate(raw_spans) if s <= start < e), None)
        if idx is not None and correction['original'] in raw_spans[idx][2]:
            return idx

    original = correction['original']
    return next(
        (n for n, (_s, _e, w) in enumerate(raw_spans) if n not in used and original in w),
        None
    )


def classify_changes(
    raw_text: str,
    reference: str,
    corrections: List[Dict[str, Any]]
) -> Tuple[int, int, int]:
    """
    Split the engine's changes into (fixed, broke, other) by aligning the
    uncorrected OCR text to the reference word by word.

    A change is 'fixed' if the word the engine wrote is what the reference has
    at that position, 'broke' if the reference already agreed with the OCR text
    the engine overwrote, and 'other' if the word was wrong before and is still
    not right -- which is neither a win nor a regression, just noise moved
    around.

    Alignment is difflib over whitespace-split words, so this is only
    meaningful where the OCR text and reference are broadly parallel; badly
    misaligned pages inflate 'other' rather than the other two counts.
    """
    raw_spans = _word_spans(raw_text)
    raw_words = [w for _, _, w in raw_spans]
    ref_words = reference.split()

    aligned: Dict[int, str] = {}
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, raw_words, ref_words).get_opcodes():
        if tag in ('equal', 'replace') and (i2 - i1) == (j2 - j1):
            for k in range(i2 - i1):
                aligned[i1 + k] = ref_words[j1 + k]

    ref_word_set = set(ref_words)
    fixed = broke = other = 0
    used: set = set()
    for corr in corrections:
        original, replacement = corr['original'], corr['correction']

        # heal_split_tokens reports a merge as original="w1 w2" -> "w1w2",
        # which spans two word slots and so has no single index to align to.
        # Judge it directly against the reference vocabulary instead: if the
        # reference has the halves separately, the merge destroyed a real word
        # boundary; if it has the joined form, the merge repaired a split.
        if ' ' in original:
            halves = original.split()
            if all(any(h in rw for rw in ref_word_set) for h in halves):
                broke += 1
            elif any(replacement in rw for rw in ref_word_set):
                fixed += 1
            else:
                other += 1
            continue

        idx = _locate(corr, raw_spans, used)
        if idx is None or idx not in aligned:
            other += 1
            continue
        used.add(idx)

        ref_word = aligned[idx]
        # The aligned reference word can carry punctuation the token doesn't.
        if replacement in ref_word:
            fixed += 1
        elif original in ref_word:
            broke += 1
        else:
            other += 1
    return fixed, broke, other


# ─────────────────────────────────────────────────────────────
# Evaluation
# ─────────────────────────────────────────────────────────────

def evaluate(docs: List[Doc]) -> Dict[str, Any]:
    total = {'cer': 0.0, 'wer': 0.0, 'fixed': 0, 'broke': 0, 'other': 0, 'changes': 0}
    per_doc = []
    start = time.time()

    for doc in docs:
        corrected_lines, corrections = correct_layout_lines(doc.lines)
        hyp = '\n'.join(l['text'] for l in corrected_lines if not l.get('is_likely_non_text'))
        cer = char_error_rate(hyp, doc.reference)
        wer = word_error_rate(hyp, doc.reference)
        fixed, broke, other = classify_changes(doc.raw_text, doc.reference, corrections)

        total['cer'] += cer
        total['wer'] += wer
        total['fixed'] += fixed
        total['broke'] += broke
        total['other'] += other
        total['changes'] += len(corrections)
        per_doc.append({
            'name': doc.name,
            'cer': cer,
            'wer': wer,
            'baseline_cer': char_error_rate(doc.raw_text, doc.reference),
            'fixed': fixed, 'broke': broke, 'other': other,
        })

    n = len(docs)
    return {
        'cer': total['cer'] / n,
        'wer': total['wer'] / n,
        'fixed': total['fixed'],
        'broke': total['broke'],
        'other': total['other'],
        'changes': total['changes'],
        'secs': time.time() - start,
        'per_doc': per_doc,
    }


def baseline_metrics(docs: List[Doc]) -> Dict[str, float]:
    """CER/WER of the uncorrected input -- what correction has to beat."""
    cer = sum(char_error_rate(d.raw_text, d.reference) for d in docs) / len(docs)
    wer = sum(word_error_rate(d.raw_text, d.reference) for d in docs) / len(docs)
    return {'cer': cer, 'wer': wer}


def report(base: Dict[str, float], res: Dict[str, Any], verbose: bool) -> None:
    print(f"\n{'':18} {'CER':>8} {'WER':>8} {'fixed':>7} {'broke':>7} {'other':>7} {'secs':>7}")
    print('-' * 68)
    print(f"{'uncorrected':18} {base['cer']:8.4f} {base['wer']:8.4f} {'—':>7} {'—':>7} {'—':>7} {'—':>7}")
    print(f"{'rule engine':18} {res['cer']:8.4f} {res['wer']:8.4f} "
          f"{res['fixed']:7d} {res['broke']:7d} {res['other']:7d} {res['secs']:7.1f}")

    d_cer = res['cer'] - base['cer']
    d_wer = res['wer'] - base['wer']
    print(f"{'delta':18} {d_cer:+8.4f} {d_wer:+8.4f}")

    print(f"\n{res['changes']} changes total. "
          f"Precision (fixed / (fixed+broke)) = "
          f"{res['fixed'] / max(1, res['fixed'] + res['broke']):.3f}")
    if res['broke'] > res['fixed']:
        print("WARNING: more words broken than fixed. This is a regression for the "
              "corpus goal regardless of what CER did.")

    if verbose:
        print(f"\n{'page':44} {'base':>7} {'after':>7} {'fix':>4} {'brk':>4}")
        print('-' * 70)
        for d in sorted(res['per_doc'], key=lambda x: -(x['baseline_cer'] - x['cer'])):
            print(f"{d['name'][:44]:44} {d['baseline_cer']:7.4f} {d['cer']:7.4f} "
                  f"{d['fixed']:4d} {d['broke']:4d}")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--pages', nargs='+', metavar='IMG',
                    help='page images with same-basename .txt ground truth')
    ap.add_argument('--text-pair', nargs=2, metavar=('NOISY', 'CLEAN'),
                    help='an already-OCRd text file and its reference')
    ap.add_argument('--synthetic', type=int, metavar='N',
                    help='corrupt N clean corpus lines and measure recovery')
    ap.add_argument('--corpus', default='data/corpus_literary',
                    help='corpus directory for --synthetic (default: data/corpus_literary)')
    ap.add_argument('--noise-rate', type=float, default=0.02,
                    help='per-character corruption rate for --synthetic (default: 0.02)')
    ap.add_argument('--seed', type=int, default=20260901)
    ap.add_argument('--lang', default='kan')
    ap.add_argument('--psm', type=int, default=6)
    ap.add_argument('--oem', type=int, default=1)
    ap.add_argument('--verbose', '-v', action='store_true', help='per-page breakdown')
    ap.add_argument('--json-out', metavar='PATH', help='also write the full result as JSON')
    args = ap.parse_args()

    if not (args.pages or args.text_pair or args.synthetic):
        ap.error('one of --pages, --text-pair or --synthetic is required')

    print('Loading dictionary and n-gram model...')
    init_pipeline()

    if args.pages:
        paths = []
        for pattern in args.pages:
            paths.extend(sorted(glob.glob(pattern)) if any(c in pattern for c in '*?[') else [pattern])
        print(f'OCR-ing {len(paths)} page image(s)...')
        docs = load_page_docs(paths, args.lang, args.psm, args.oem)
    elif args.text_pair:
        docs = load_text_pair(*args.text_pair)
    else:
        print(f'Building {args.synthetic} synthetic noisy lines '
              f'(rate={args.noise_rate}) from {args.corpus}...')
        docs = load_synthetic_docs(args.synthetic, args.corpus, args.noise_rate, args.seed)

    if not docs:
        raise SystemExit('No documents to evaluate.')

    print(f'{len(docs)} document(s) loaded.')
    base = baseline_metrics(docs)
    res = evaluate(docs)
    report(base, res, args.verbose)

    if args.json_out:
        with open(args.json_out, 'w', encoding='utf-8') as fh:
            json.dump({'baseline': base, 'result': res}, fh, ensure_ascii=False, indent=2)
        print(f'\nWrote {args.json_out}')

    return 0


if __name__ == '__main__':
    sys.exit(main())
